### PR TITLE
[lab-mysql-select] rute correia

### PR DESCRIPTION
**Pull request by aariops**
sql fun fun fun

### CODE REVIEW

**Comment by aariops** [comment]
:tada:

**Comment by aariops** [comment]
only finished challenge 1 :sweat_smile:

**Comment by aariops** [comment]
now really finished

**Comment by MattiaLobascio** [comment]
Lab checked, good job!

**Challenge 3**
The logic of the query is correct, you just missed to include the total quantity of book sold to date (ytd_sales as TOTAL) by each author, and thus use the GROUP BY command as well:

**SELECT authors.au_id, authors.au_lname, authors.au_fname, sum(titles.ytd_sales) as TOTAL
   FROM pubblications.titleauthor
   INNER JOIN pubblications.authors on titleauthor.au_id = authors.au_id 
   INNER JOIN pubblications.titles on titleauthor.title_id = titles.title_id
   GROUP BY authors.au_id
   ORDER BY TOTAL DESC
   LIMIT 3;**

**Challenge 4**
Same as above, but with the due changes ;)...

Keep up the good work!

**Comment by ta-data-lis** [comment]
Lab checked, good job!

**Challenge 3**
The logic of the query is correct, you just missed to include the total quantity of book sold to date (ytd_sales as TOTAL) by each author, and thus use the GROUP BY command as well:

**SELECT authors.au_id, authors.au_lname, authors.au_fname, sum(titles.ytd_sales) as TOTAL
FROM pubblications.titleauthor
INNER JOIN pubblications.authors on titleauthor.au_id = authors.au_id
INNER JOIN pubblications.titles on titleauthor.title_id = titles.title_id
GROUP BY authors.au_id
ORDER BY TOTAL DESC
LIMIT 3;**

**Challenge 4**
Same as above, but with the due changes ;)...

Keep up the good work!

**Pull request closed without merging**
